public enum SGDs {
    NoPoverty,
    ZeroHunger,
    GoodHealthAndWellBeing,
    QualityEducation,
    GenderEquality,
    CleanWaterAndSanitation,
    AffordableAndCleanEnergy,
    DecentWorkAndEconomicGrowth,
    IndustryInnovationAndInfrastructure,
    RecudedInequalities,
    SustainableCitiesAndCommunities,
    ResponsibleConsumptionAndProduction,
    ClimateAction,
    LifeBelowWater,
    LifeOnLand,
    PeaceJusticeAndStrongInstitutions,
    PartnershipsForTheGoals
}
